// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:give_a_break/data/models/app_limit_model.dart';
import 'package:give_a_break/data/models/app_settings_model.dart';
import 'package:give_a_break/data/models/parental_settings_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppLimitModelAdapter());
    registerAdapter(AppSettingsModelAdapter());
    registerAdapter(ParentalSettingsModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppLimitModelAdapter());
    registerAdapter(AppSettingsModelAdapter());
    registerAdapter(ParentalSettingsModelAdapter());
  }
}
